(function(){'use strict';const mount=document.querySelector('#quiz');if(!mount)return;const questions=[
  {q:'Tu banco llama y pide el código que acaba de llegar por SMS. ¿Qué haces?',a:['Se lo digo para proteger la cuenta','Cuelgo y contacto al banco por su canal oficial','Espero que vuelvan a llamar'],correct:1,e:'Los códigos de acceso son privados. Un supuesto empleado no debe pedírtelos.'},
  {q:'Un familiar escribe desde un número nuevo y necesita dinero urgente.',a:['Transfiero una cantidad pequeña','Llamo al número anterior o a otro familiar','Le pido una foto por el mismo chat'],correct:1,e:'Verificar por otro canal evita depender del contacto posiblemente falso.'},
  {q:'Aparece un aviso inesperado que dice que tu computadora tiene virus.',a:['Instalo el programa recomendado','Llamo al teléfono del aviso','Cierro el aviso y reviso el sistema desde sus opciones'],correct:2,e:'Los avisos alarmantes pueden ser falsos. No instales ni llames desde el propio aviso.'},
  {q:'Recibes un correo con una oferta excelente y un enlace.',a:['Entro desde el enlace','Busco la tienda por mi cuenta y compruebo la oferta','Lo reenvío para preguntar'],correct:1,e:'Abrir el sitio por tu cuenta evita confiar en un enlace inesperado.'},
  {q:'¿Qué contraseña es más segura para tus cuentas importantes?',a:['La misma en todas','Una distinta para cada cuenta','Tu fecha de nacimiento'],correct:1,e:'Si una contraseña se filtra, las demás cuentas siguen protegidas cuando son diferentes.'},
  {q:'Una actualización oficial está disponible en tu celular.',a:['La pospongo siempre','La instalo desde los ajustes o tienda oficial','Busco una descarga en un mensaje'],correct:1,e:'Las actualizaciones oficiales corrigen fallos de seguridad.'},
  {q:'Una voz idéntica a la de alguien conocido pide dinero de inmediato.',a:['La voz demuestra que es real','Corto y contacto a la persona por otro canal','Pago y pregunto después'],correct:1,e:'La voz puede imitarse. Verifica siempre una solicitud inesperada de dinero.'},
  {q:'Caíste en una estafa. ¿Qué ayuda a limitar el daño?',a:['Ocultarlo por vergüenza','Esperar varios días','Cortar el contacto, avisar al banco y pedir ayuda'],correct:2,e:'Actuar pronto puede limitar las consecuencias. La culpa siempre es de quien engaña.'}
];let index=0,score=0;const live=document.createElement('p');live.className='sr-only';live.setAttribute('role','status');live.setAttribute('aria-live','polite');document.body.append(live);const render=()=>{mount.replaceChildren();if(index>=questions.length){const box=document.createElement('div');box.className='quiz-question';const h=document.createElement('h3');h.textContent='Práctica completada';const p=document.createElement('p');p.textContent=`Reconociste ${score} de ${questions.length} situaciones. No importa cuántas acertaste: estas señales se aprenden practicando.`;const restart=document.createElement('button');restart.className='button secondary';restart.textContent='Volver a practicar';restart.addEventListener('click',()=>{index=0;score=0;render()});box.append(h,p,restart);mount.append(box);try{localStorage.setItem('sd-quiz-complete','true')}catch{}return}const item=questions[index];const progress=document.createElement('p');progress.className='quiz-progress';progress.textContent=`Situación ${index+1} de ${questions.length}`;live.textContent=progress.textContent;const box=document.createElement('section');box.className='quiz-question';const h=document.createElement('h3');h.textContent=item.q;const options=document.createElement('div');options.className='quiz-options';options.setAttribute('role','group');options.setAttribute('aria-label','Opciones de respuesta');item.a.forEach((answer,i)=>{const button=document.createElement('button');button.type='button';button.textContent=answer;button.addEventListener('click',()=>answerQuestion(i,button,options,box,item));options.append(button)});box.append(h,options);mount.append(progress,box)};const answerQuestion=(selected,button,options,box,item)=>{const correct=selected===item.correct;if(correct)score++;options.querySelectorAll('button').forEach((choice,i)=>{choice.disabled=true;if(i===item.correct){choice.classList.add('correct');choice.textContent='✓ '+choice.textContent}else if(i===selected){choice.classList.add('incorrect');choice.textContent='✗ '+choice.textContent}});live.textContent=(correct?'Respuesta correcta. ':'Respuesta incorrecta. La opción correcta es: '+item.a[item.correct]+'. ')+item.e;const explanation=document.createElement('p');explanation.className='quiz-explanation';explanation.textContent=(correct?'Buena decisión. ':'Conviene elegir otra opción. ')+item.e;const next=document.createElement('button');next.className='button primary';next.textContent=index===questions.length-1?'Ver resultado':'Siguiente situación';next.addEventListener('click',()=>{index++;render();mount.scrollIntoView({block:'center'})});box.append(explanation,next);next.focus()};render()})();
